### ISSUE TITLE
Exiting VR scene

### ISSUE THREAD

**Issue by SrinivasPrabhu794** [danielesteban/dudes#1]
Hi Daniel,

How do we exit the immersive session at the moment?

There seems to be no way to exit from the scene at the moment at least when we are connected to VR via the Rift S, tethered VR

**Comment by danielesteban** [comment]
In the examples that don't override the default locomotion, you can exit VR by pressing the secondary button.
Which is the B on the right hand and Y on the left hand.
There are few examples that override the default locomotion code, though. Mainly cause I wanted to demonstrate how to do that and then the responsability of that functionality relies on the programmer of the scene.
So in some of those I prolly forgot to add the extra code and there is no way to exit VR but with the oculus button and closing the application from there.
